[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#fbf1c7'
foreground = '#3c3836'

[colors.normal]
black   = '#fbf1c7'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#7c6f64'

[colors.bright]
black   = '#928374'
red     = '#9d0006'
green   = '#79740e'
yellow  = '#b57614'
blue    = '#076678'
magenta = '#8f3f71'
cyan    = '#427b58'
white   = '#3c3836'

[font]
size = 9
#size = 10

[font.normal]
family = "DejaVuSansM Nerd Font"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi|~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Shift"

[window.padding]
x = 10
y = 10
